# Generated by Django 3.0.5 on 2020-04-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='last_interation',
        ),
        migrations.AlterField(
            model_name='activity',
            name='viewed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
