# Generated by Django 3.0.5 on 2020-04-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
