# Generated by Django 3.0.5 on 2020-04-24 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='favorites',
        ),
        migrations.AddField(
            model_name='draft',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draft',
            name='comments',
            field=models.ManyToManyField(related_name='draft', to='draft.Comment'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_drafts', to='draft.Tag'),
        ),
    ]
