# Generated by Django 3.0.7 on 2020-06-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20200612_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='abstract',
            new_name='description',
        ),
    ]
