# Generated by Django 3.0.5 on 2020-04-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20200426_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='view_count',
            new_name='hits',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='likes',
        ),
    ]
