# Generated by Django 3.0.5 on 2020-04-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20200424_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='favorited_by',
        ),
    ]
