# Generated by Django 3.0.5 on 2020-04-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_draft_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
