# Generated by Django 3.0.5 on 2020-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20200427_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-pub_date'], 'verbose_name': 'draft', 'verbose_name_plural': 'drafts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='draft', to='draft.Comment'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_drafts', to='draft.Tag'),
        ),
    ]
