# Generated by Django 3.0.5 on 2020-04-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20200419_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='tags',
            field=models.ManyToManyField(to='draft.Tag'),
        ),
    ]
