# Generated by Django 3.0.5 on 2020-04-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20200420_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='name',
        ),
    ]
