# Generated by Django 3.0.7 on 2020-06-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_draft_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='draft',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_drafts', to='draft.Tag'),
        ),
    ]
