# Generated by Django 3.0.5 on 2020-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_auto_20200420_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
