# Generated by Django 3.0.4 on 2020-03-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200331_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='username',
        ),
        migrations.AddField(
            model_name='blog',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
