# Generated by Django 3.0.5 on 2020-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='bio',
            field=models.TextField(max_length=160, null=True),
        ),
    ]
