# Generated by Django 3.0.5 on 2020-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_remove_draft_favorited_by'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='avatar',
        ),
        migrations.AddField(
            model_name='blog',
            name='favorited_drafts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='draft.Draft'),
        ),
    ]
