# Generated by Django 3.0.5 on 2020-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200420_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='bio',
            field=models.TextField(default='{{ get_from_github }}', max_length=160),
        ),
    ]
