# Generated by Django 3.0.5 on 2020-04-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200426_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='favorited_drafts',
        ),
    ]
