# Generated by Django 3.0.4 on 2020-04-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200331_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='felipe', max_length=255),
            preserve_default=False,
        ),
    ]
