# Generated by Django 3.0.4 on 2020-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200402_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='raw_content_url',
            new_name='github_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
